HAI 1.3


CAN HAS STDIO? 

VISIBLE "SILLY ERA STARTS NOW"

I HAS A  MESSAGE ITZ "hewwo"
VISIBLE MESSAGE

I HAS A SECRET 
GIMMEH SECRET

BOTH SAEM SECRET AN "IMA CAT :33"
   YA RLY
     VISIBLE "YOU ARE A CAT!!"
   MEBBE BOTH SAEM SECRET AN "I am a dog"
      VISIBLE "KYS"
    NO WAI 
      VISIBLE "YOU NOT A KITTAY AHHHH"

KTHXBYE